import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abhishekh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} overflow-x-hidden min-h-screen flex flex-wrap flex-col justify-between`}  >
      <Navbar />
      {children}
      <Toaster />
      <Footer />
      
      
      </body>
    </html>
  );
}